package:
  name: tszip
  version: 0.3.1
  tag:
    - always
  top-level:
    - tszip

source:
  url: https://files.pythonhosted.org/packages/ac/cf/046c626d9d4acc9af08ea2492d9b4ba221a15983abee5db5da2f5d192295/tszip-0.3.1-py3-none-any.whl
  sha256: 459ea5d2cf456840c86b6a119f2da7b6e41b09d302169a9ea000ec5bbf6037b2

requirements:
  run:
    - numpy
    - humanize
    - tskit
    - zarr

about:
  home: https://tskit.dev/tszip
  PyPI: https://pypi.org/project/tszip
  summary: Compression utilities for tree sequences
  license: MIT
