package:
  name: humanize
  version: 4.15.0
  top-level:
    - humanize

source:
  url: https://files.pythonhosted.org/packages/c5/7b/bca5613a0c3b542420cf92bd5e5fb8ebd5435ce1011a091f66bb7693285e/humanize-4.15.0-py3-none-any.whl
  sha256: b1186eb9f5a9749cd9cb8565aee77919dd7c8d076161cf44d70e59e3301e1769

about:
  home: https://github.com/python-humanize/humanize
  PyPI: https://pypi.org/project/humanize
  summary: Python humanize utilities
  license: MIT
