name: Trigger site rebuild

on:
  push:
    branches: [main]
    tags:
      - '*'


jobs:
  trigger-site-rebuild:
    name: Docs
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Trigger docs site rebuild
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST https://api.github.com/repos/tskit-dev/tskit-site/dispatches \
                    -H 'Accept: application/vnd.github.everest-preview+json' \
                    -u AdminBot-tskit:${{ secrets.ADMINBOT_TOKEN }} \
                    --data '{"event_type":"build-docs"}'
